USE [master]
GO
/****** Object:  Database [Posgrado]    Script Date: 22/4/2024 10:52:29 ******/
CREATE DATABASE [Posgrado]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Posgrado', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Posgrado.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Posgrado_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Posgrado_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Posgrado] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Posgrado].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Posgrado] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Posgrado] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Posgrado] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Posgrado] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Posgrado] SET ARITHABORT OFF 
GO
ALTER DATABASE [Posgrado] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Posgrado] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Posgrado] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Posgrado] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Posgrado] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Posgrado] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Posgrado] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Posgrado] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Posgrado] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Posgrado] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Posgrado] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Posgrado] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Posgrado] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Posgrado] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Posgrado] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Posgrado] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Posgrado] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Posgrado] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Posgrado] SET  MULTI_USER 
GO
ALTER DATABASE [Posgrado] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Posgrado] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Posgrado] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Posgrado] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Posgrado] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Posgrado] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Posgrado] SET QUERY_STORE = OFF
GO
USE [Posgrado]
GO
/****** Object:  Table [dbo].[Alumno]    Script Date: 22/4/2024 10:52:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Alumno](
	[DNI] [varchar](10) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
 CONSTRAINT [PK_Alumno] PRIMARY KEY CLUSTERED 
(
	[DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AlumnoEmail]    Script Date: 22/4/2024 10:52:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlumnoEmail](
	[DNIAlumno] [varchar](10) NOT NULL,
	[Email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_AlumnoEmail] PRIMARY KEY CLUSTERED 
(
	[DNIAlumno] ASC,
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AlumnoTelefono]    Script Date: 22/4/2024 10:52:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlumnoTelefono](
	[DNIAlumno] [varchar](10) NOT NULL,
	[Telefono] [varchar](20) NOT NULL,
 CONSTRAINT [PK_AlumnoTelefono] PRIMARY KEY CLUSTERED 
(
	[DNIAlumno] ASC,
	[Telefono] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Calificacion]    Script Date: 22/4/2024 10:52:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Calificacion](
	[DNIAlumno] [varchar](10) NOT NULL,
	[CodMateria] [int] NOT NULL,
	[Nota] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Calificacion] PRIMARY KEY CLUSTERED 
(
	[DNIAlumno] ASC,
	[CodMateria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Materia]    Script Date: 22/4/2024 10:52:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materia](
	[CodMateria] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
 CONSTRAINT [PK_Materia] PRIMARY KEY CLUSTERED 
(
	[CodMateria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AlumnoEmail]  WITH CHECK ADD  CONSTRAINT [FK_AlumnoEmail_Alumno] FOREIGN KEY([DNIAlumno])
REFERENCES [dbo].[Alumno] ([DNI])
GO
ALTER TABLE [dbo].[AlumnoEmail] CHECK CONSTRAINT [FK_AlumnoEmail_Alumno]
GO
ALTER TABLE [dbo].[AlumnoTelefono]  WITH CHECK ADD  CONSTRAINT [FK_AlumnoTelefono_Alumno] FOREIGN KEY([DNIAlumno])
REFERENCES [dbo].[Alumno] ([DNI])
GO
ALTER TABLE [dbo].[AlumnoTelefono] CHECK CONSTRAINT [FK_AlumnoTelefono_Alumno]
GO
ALTER TABLE [dbo].[Calificacion]  WITH CHECK ADD  CONSTRAINT [FK_Calificacion_Alumno] FOREIGN KEY([DNIAlumno])
REFERENCES [dbo].[Alumno] ([DNI])
GO
ALTER TABLE [dbo].[Calificacion] CHECK CONSTRAINT [FK_Calificacion_Alumno]
GO
ALTER TABLE [dbo].[Calificacion]  WITH CHECK ADD  CONSTRAINT [FK_Calificacion_Materia] FOREIGN KEY([CodMateria])
REFERENCES [dbo].[Materia] ([CodMateria])
GO
ALTER TABLE [dbo].[Calificacion] CHECK CONSTRAINT [FK_Calificacion_Materia]
GO
USE [master]
GO
ALTER DATABASE [Posgrado] SET  READ_WRITE 
GO
